twist_mux:
  ros__parameters:
    output_topic: /cmd_vel

    topics:
      keyboard:
        topic: /cmd_vel_keyboard
        timeout: 0.3
        priority: 100
      nav2:
        topic: /cmd_vel_safe
        timeout: 0.5
        priority: 50

    locks:
      e_stop:
        topic: /e_stop
        timeout: 0.0
        priority: 255
